version: '4'
services:
  mariadb:
    image: mariadb:10.4.8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data: